# .github/workflows/ci.yml
name: CI

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt --upgrade pip
          pip install pytest
          echo ${GITHUB_WORKSPACE}
      - name: Create env file
        run: |
          touch .env
          echo PYTHONPATH="${GITHUB_WORKSPACE}/src/python" >> .env
          cat .env
      - name: Unittest
        run: |
          pytest
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
