# .github/workflows/scheduled_test.yml
name: Test call windwords repository function

on:
  schedule:
    # Runs "every five minutes" (see https://crontab.guru)
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Run
        run: |
          python ./src/python/windwords/test_github_action.py
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
        